# The line numbers in this data file refer to specific locations within
# exception_test_case.py where functions are called or exceptions are
# raised.  If the source file is ever changed in a way that affects
# line numbering, this data file must be updated accordingly.
[
    "there will be no breakfast today",
    "    at test_tracebacks_indent line 103 in exception_test_case.py",
    "    at make_breakfast line 43 in exception_test_case.py",
    "could not make an omlette",
    "    at make_breakfast line 41 in exception_test_case.py",
    "    at make_omlette line 36 in exception_test_case.py",
    "there are no eggs",
    "    at make_omlette line 34 in exception_test_case.py",
    "    at get_eggs line 29 in exception_test_case.py"
]
